version: "3"

services:
  feature-flags:
    container_name: basestack-feature-flags
    build:
      context: .
      dockerfile: ./apps/feature-flags/Dockerfile
    env_file:
      - ./apps/feature-flags/.env
    restart: always
    ports:
      - 3000:3000
    networks:
      - app_network

# Define a network, which allows containers to communicate
# with each other, by using their container name as a hostname
networks:
  app_network:
    external: true
