services:
  - type: web
    name: basestack-landing-page
    rootDir: apps/landing-page
    env: static
    buildCommand: cd ../.. && yarn install && yarn build:packages; cd apps/landing-page/ && yarn build && yarn next export
    staticPublishPath: out
    pullRequestPreviewsEnabled: true
    envVars:
      - key: SKIP_INSTALL_DEPS
        value: true # disables npm install to use yarn
      - key: NEXT_PUBLIC_PIWIK_PRO_ACCOUNT_URL
        sync: false # placeholder for a value to be added in the dashboard
      - key: NEXT_PUBLIC_PIWIK_PRO_CONTAINER_ID
        sync: false # placeholder for a value to be added in the dashboard
  - type: web
    name: basestack-feature-flags-app
    rootDir: apps/feature-flags
    env: node
    buildCommand: cd ../.. && yarn && yarn build:packages; cd apps/feature-flags/ && yarn build:deploy
    startCommand: yarn start
    staticPublishPath: .next
    pullRequestPreviewsEnabled: false
    plan: free
    autoDeploy: true
    healthCheckPath: /api/trpc/healthcheck
    envVars:
      - key: SKIP_INSTALL_DEPS
        value: true # disables npm install to use yarn
      - key: DATABASE_URL
        fromDatabase:
          name: basestack-feature-flags-db
          property: connectionString
      - key: MIGRATE_DATABASE_URL
        sync: false
      - key: GITHUB_CLIENT_ID
        sync: false
      - key: GITHUB_CLIENT_SECRET
        sync: false
      - key: NEXTAUTH_SECRET
        sync: false
      - key: NEXTAUTH_URL
        sync: false
  - type: pserv
    name: basestack-feature-flags-db-pgbouncer
    env: docker
    plan: free
    repo: https://github.com/render-oss/docker-pgbouncer
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: basestack-feature-flags-db
          property: connectionString
      - key: POOL_MODE
        value: transaction
      - key: SERVER_RESET_QUERY
        value: DISCARD ALL
      - key: MAX_CLIENT_CONN
        value: 500
      - key: DEFAULT_POOL_SIZE
        value: 50
databases:
  - name: basestack-feature-flags-db
    plan: free
