services:
  - type: web
    name: basestack-landing-page
    # rootDir: no need to specify rootDir
    runtime: static
    buildCommand: yarn; yarn deploy:landing-page
    staticPublishPath: apps/landing-page/out
    pullRequestPreviewsEnabled: false
    envVars:
      - key: SKIP_INSTALL_DEPS
        value: true # disables npm install to use yarn
      - key: NODE_VERSION
        value: 16.8.0
      - key: NEXT_PUBLIC_EMAIL_SERVICE
        sync: false
      - key: NEXT_PUBLIC_UMAMI_WEBSITE_ID
        sync: false
  - type: web
    name: basestack-docs
    # rootDir: no need to specify rootDir
    runtime: static
    buildCommand: yarn; yarn deploy:docs
    staticPublishPath: apps/docs/out
    pullRequestPreviewsEnabled: false
    envVars:
      - key: SKIP_INSTALL_DEPS
        value: true # disables npm install to use yarn
      - key: NODE_VERSION
        value: 16.8.0
  - type: web
    name: basestack-feature-flags-app
    # rootDir: no need to specify rootDir
    runtime: node
    buildCommand: yarn; yarn deploy:feature-flags
    startCommand: yarn start
    pullRequestPreviewsEnabled: false
    plan: starter
    autoDeploy: true
    healthCheckPath: /api/trpc/healthcheck
    envVars:
      - key: SKIP_INSTALL_DEPS
        value: true # disables npm install to use yarn
      - key: DATABASE_URL
        sync: false
      - key: DIRECT_DATABASE_URL
        fromDatabase:
          name: basestack-feature-flags-db
          property: connectionString
      - key: NEXTAUTH_SECRET
        sync: false
      - key: NEXTAUTH_URL
        sync: false
      - key: GITHUB_CLIENT_ID
        sync: false
      - key: GITHUB_CLIENT_SECRET
        sync: false
      - key: AUTH0_CLIENT_ID
        sync: false
      - key: AUTH0_CLIENT_SECRET
        sync: false
      - key: AUTH0_DOMAIN
        sync: false
      - key: API_RATE_LIMIT_MAX
        value: 60
      - key: API_RATE_LIMIT_WINDOW_MS
        value: 60*1000
      - key: API_RATE_LIMIT_UNIQUE_TOKEN_PER_SECOND
        value: 1000
      - key: API_ACCESS_CONTROL_ALLOW_ORIGIN
        sync: false
  - type: pserv
    name: basestack-feature-flags-db-pgbouncer
    runtime: docker
    plan: starter
    repo: https://github.com/render-oss/docker-pgbouncer
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: basestack-feature-flags-db
          property: connectionString
      - key: POOL_MODE
        value: transaction
      - key: SERVER_RESET_QUERY
        value: DISCARD ALL
      - key: MAX_CLIENT_CONN
        value: 500
      - key: DEFAULT_POOL_SIZE
        value: 50
databases:
  - name: basestack-feature-flags-db
    databaseName: basestack-feature-flags-db
    plan: starter
