name: LANDING-PAGE-CI

on:
  push:
    branches: ["develop"]
  pull_request:
    types: [opened, synchronize]

jobs:
  build:
    name: Landing Page - Lint, Test and Build
    timeout-minutes: 15
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
      - name: Check out code
        uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - name: Setup Node.js environment
        uses: actions/setup-node@v2
        with:
          node-version: 21.1.0
          cache: "yarn"

      - name: Install dependencies
        run: yarn

      - name: Build packages
        run: yarn build:packages

      - name: Lint Landing Page
        run: yarn lint --filter=landing-page...

      - name: Test Landing Page
        run: yarn test --filter=landing-page...

      - name: Build Landing Page
        run: yarn build:landing-page
